#ifndef CV2_Errors_h
#define CV2_Errors_h

#include <Arduino.h>

enum {
	PATCH_SAVE_BUFFER_TOO_SMALL, // 0
	PATCH_NUMBER_INVALID, // 1
	PATCH_READ_FROM_EEPROM_FAILED, // 2
	PATCH_WRITE_TO_EEPROM_FAILED, // 3
	HEADER_WRITE_TO_EEPROM_FAILED, // 4
	PATCH_READ_HEADER_FROM_EEPROM_FAILED, // 5
	PATCH_CHECKSUM_ERROR, // 6
	NO_FREE_PATCHES
};

#endif
